### ISSUE TITLE
[Feature] Make `hover` animation optional

### ISSUE THREAD

**Issue by hrueger** [colorswall/CSS-file-icons#8]
Hi @colorswall,
first of all, thanks for this very useful and nice looking library.

I'd like to be able to disable the `hover` animation. Maybe with `.fi-no-hover` or if this would be the default we could enable it with `.fi-hover`?

I'll create a PR for this once you say which way you prefer.

**Comment by colorswall** [comment]
Please add `.fi-no-hover`
